<?php declare(strict_types=1);

namespace Palmyr\GitHooks\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\Filesystem;

class LinkCommand extends Command
{

    protected Filesystem $filesystem;

    protected string $rootDir;

    public function __construct(
        Filesystem $filesystem,
        string $rootDir
    )
    {
        $this->filesystem = $filesystem;
        $this->rootDir = $rootDir;
        parent::__construct('app:link');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}