<?php declare(strict_types=1);

namespace Palmyr\GitHooks\Command;

use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class PreCommitHookCommand extends AbstractGitHookCommand
{

    public function __construct()
    {
        parent::__construct('git:pre_commit');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}