services:

  filesystem:
    class: Symfony\Component\Filesystem\Filesystem

  app.command.link:
    class: Palmyr\GitHooks\Command\LinkCommand
    arguments:
      - '@filesystem'
      - '%root_dir%'
    tags: ['command']

  app.command.pre_commit:
    class: Palmyr\GitHooks\Command\PreCommitHookCommand
    tags: ['command']
