services:

  file_locator:
    public: true
    class: Symfony\Component\Config\FileLocator

  filesystem:
    class: Symfony\Component\Filesystem\Filesystem

  app.command.enable:
    class: Palmyr\GitHooks\Command\EnableHooksCommand
    arguments:
      - '@filesystem'
      - '%root_directory%'
    tags: ['command']

  app.command.disable:
    class: Palmyr\GitHooks\Command\DisableHooksCommand
    arguments:
      - '@filesystem'
      - '%root_directory%'
    tags: [ 'command' ]

  shell_command.service.filesystem:
    class: Palmyr\CommonUtils\FileSystem\FileSystem

  shell_command.factory.command:
    class: Palmyr\CommonUtils\Shell\Factory\ShellCommandFactory
    arguments:
      - "@shell_command.service.filesystem"
