#!/bin/sh

HOOK_DIRECTORY=$(dirname $(readlink -f $0))

. ${HOOK_DIRECTORY}/commonutils.sh

${ROOT_DIRECTORY}/vendor/bin/hook git:pre_commit ${BRANCH} "applypatch-msg"

exit 0

#
# An example hook script to check the commit log message taken by
# applypatch from an e-mail message.
#
# The hook should exit with non-zero status after issuing an
# appropriate message if it wants to stop the commit.  The hook is
# allowed to edit the commit message file.
#
# To enable this hook, rename this file to "applypatch-msg".

. git-sh-setup
commitmsg="$(git rev-parse --git-path hooks/commit-msg)"
test -x "$commitmsg" && exec "$commitmsg" ${1+"$@"}
:
