#!/bin/sh

HOOK_DIRECTORY=$(dirname $(readlink -f $0))

. ${HOOK_DIRECTORY}/commonutils.sh

${ROOT_DIRECTORY}/vendor/bin/hook git:default ${BRANCH} "pre-applypath"

exit 0

#
# An example hook script to verify what is about to be committed
# by applypatch from an e-mail message.
#
# The hook should exit with non-zero status after issuing an
# appropriate message if it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-applypatch".

. git-sh-setup
precommit="$(git rev-parse --git-path hooks/pre-commit)"
test -x "$precommit" && exec "$precommit" ${1+"$@"}
:
